### ISSUE TITLE
Implementare UC CRUD Gestione Archivio Taglie

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-01#11]
Implementare la gestione CRUD per l'entità Taglia.
e-commerce.CRUD
e-commerce.Entità.Anagrafiche.Anagrafiche

**Comment by rdef98** [comment]
d613cdd607d94955de9527fa287908c1dce89611 - Aggiornamento 1

**Comment by rdef98** [comment]
1cc20d79386fa4ad555cd7efba0e97ba2c96e617 - Aggiornamento 2

**Comment by rdef98** [comment]
e5da429f562664e5e8d9e7963274f071772ba8fd - Aggiornamento 3

**Comment by luca-lezzerini** [comment]
Dovete fare tutto ancora
