### ISSUE TITLE
Creare struttura cartelle Spring

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/ecomm-jpr-01#14]
controller
service
service.impl
repository
model
dto

**Comment by luca-lezzerini** [comment]
Poiché le cartelle vuote non sono commitatte da Git, bisogna mettere in ogni cartella un file testo vuoto leggimi.txt

**Comment by dinodipe** [comment]
Creare struttura cartelle Spring#14   2b2fa00

**Comment by luca-lezzerini** [comment]
Non risulta creata model, vedere Problemi apertura Server #17

**Comment by dinodipe** [comment]
Il problema è stato risolto
