### ISSUE TITLE
Errori imprevisti

### ISSUE THREAD

**Issue by Prisoscar** [luca-lezzerini/ecomm-jpr-01#16]
![errori](https://user-images.githubusercontent.com/67907720/89272180-1103ce80-d63e-11ea-9216-6425e1db762c.PNG)

Prof dopo aver messo gli aggiornamenti su app modules ts e dopo aver fatto il push riaprendo il progetto da errore su tutti gli import, non capisco il perché

**Comment by luca-lezzerini** [comment]
Probabilmente non ha reinstallato i moduli di angular.
Provi dalla cartella di progetto client ad eseguire: npm i @angular/cli
