### ISSUE TITLE
Problemi apertura Server

### ISSUE THREAD

**Issue by dinodipe** [luca-lezzerini/ecomm-jpr-01#17]
Buongiorno Prof, riaprendo da Netbeans il server, non è possibile farlo; inoltre manca il package "model".

**Comment by luca-lezzerini** [comment]
Probabilmente non avete fatto pull oppure il ticket Creare struttura cartelle Spring #14 non è stato risolto. Ho riaperto il ticket Creare struttura cartelle Spring #14

**Comment by luca-lezzerini** [comment]
Nei ticket non si saluta. Ma si descrive il problema nel dettaglio.
Come faccio a capire il problema se mi viene detto solo"riaprendo da Netbeans il server, non è possibile farlo"? Non potrebbe darmi il log degli errori?

**Comment by dinodipe** [comment]
Il problema è stato risolto, qualcuno aveva cancellato dei file
