### ISSUE TITLE
progetto spring color gruppo 1

### ISSUE THREAD

**Issue by VorzilloAlessandro** [luca-lezzerini/ecomm-jpr-01#23]

**Comment by VorzilloAlessandro** [comment]
-Prisacar farà il model

**Comment by VorzilloAlessandro** [comment]
-wodke e casagrande faranno il controller

**Comment by Tomislaw-design** [comment]
il ControllerColor ed il ServiceColor parte server portato termine(Alessandra+Silvia+Tomasz).
Abbiamo bisogno di delucidazioni circa GitHub per capire meglio come aggiornare il progetto in comune perché abbiamo avuto qualche difficoltà.(non riuscivo ad aggiornare la parte che ho fatto(Tomasz))
