### ISSUE TITLE
progetto cg

### ISSUE THREAD

**Issue by VorzilloAlessandro** [luca-lezzerini/ecomm-jpr-01#24]
-Prisacar : model.
-Vorzillo: repository.
-Casagrande e wodke: controller.
-Di Carlo: service.

**Comment by Prisoscar** [comment]
Io la parte mia credo di averla fatta 9bcc6ff

**Comment by Prisoscar** [comment]
Ragazzi ieri notte non sono riuscito a dormire e ho provato a fare tutti gli altri casi d'uso, vedete se vi vanno a tutti, nel caso potete anche chiudere la issue del prof
