### ISSUE TITLE
Chiarimenti Tecnici

### ISSUE THREAD

**Issue by ago24** [luca-lezzerini/ecomm-jpr-01#25]
Lato server abbiamo creato un array di tipo categoria e non riusciamo a collegarlo all'array lato client. A seguire la parte di codice:
 let p = new CategoriaDto(this.id, this.descrizione);
    let ox: Observable<CategoriaDto> =
      this.http.post(this.urlHost + "/aggiungiCategoria", p);
    let ss: Subscription = ox.subscribe(
      r => this.arr = r.
    );
  }

**Comment by luca-lezzerini** [comment]
Lato server dovreste usare List<Categoria> ma dentro un DTO.
Lato client non avete fornito il parametro di tipo a Observable e Post che dovrebbero essere, entrambi, di tipo Categoria[].
La prossima volta copiate e incollate anche il codice lato server o, meglio ancora, allegate i file di entrambi
