### ISSUE TITLE
Unificazione credenziali di accesso MySQL e nome DB

### ISSUE THREAD

**Issue by rdef98** [luca-lezzerini/ecomm-jpr-01#32]
Riporto di seguito le istruzioni step-by-step per modificare le proprie credenziali, in modo da renderle univoche in ogni nostro dispositivo e non dover ricorrere ogni volta a modifiche nei riguardi del file "application.properties" all' interno del progetto Spring.

*WINDOWS*

1) Eseguire XAMPP, avviando MySQL

2) Eseguire HeidiSQL, accedere con le credenziali attuali

3) Modificare le credenziali di TUTTI gli utenti "root" presenti all' interno della scheda che vi si presenterà a seguito del click sull' icona cerchiata nell' immagine sottostante (1)
![Immagine](https://user-images.githubusercontent.com/67907577/89398110-fc443b00-d710-11ea-8150-e7ddef52c755.png)

4) Inserire "root" come password per tutti e 3 gli utenti root, ripeterla nel campo seguente e salvare una volta per utente
![Immagine0](https://user-images.githubusercontent.com/67907577/89398545-89878f80-d711-11ea-98bb-3360a448b6e7.png)

5) Tornare su XAMPP, cliccare sul tasto "Config" alla destra di Apache e selezionare il file "phpMyAdmin (config.inc.php)"

6) Cercare la voce ['password'] = '' (tra gli ultimi due apicetti potreste già avere la vostra password) e sostituirla con 'root'
![Immagine1](https://user-images.githubusercontent.com/67907577/89398844-ec792680-d711-11ea-9ab7-8d22e6d30b96.png)

7) Accedere nuovamente ad HeidiSQL, ora impostato con password "root" (senza apicetti)

8) Creare il database "db-ecom" (senza apicetti) cliccando sulla prima voce con il destro (quella da cui "scendono" quindi tutte le altre), sulla colonna di sinistra e selezionare Nuovo> Database

9) Accedere al progetto Spring su NetBeans ed accedere al file "application.properties", situato in Other Sources> src/main/resources> <default package>>application.properties

10) Modificare o assicurarsi della correttezza delle prime tre stringhe, che dovrebbero riportare quanto segue:

spring.datasource.url = jdbc:mysql://localhost:3306/db-ecom
spring.datasource.username = root
spring.datasource.password = root

*MAC OS X*

@Tomislaw-design 
@silviacasa68 

In quanto non dispongo di un dispositivo Mac OS X, vi darò delle indicazioni più generiche, in ogni caso vi chiedo la cortesia di aprirmi due ticket, uno ciascuno, in modo da potervi aiutare da remoto e da poter intervenire assieme a voi per "allinearvi" con il resto del project work.

1) Eseguire XAMPP

2) Avviare MySQL ed Apache

3) Accedere a phpMyAdmin

4) Cliccare su "Nuovo", sulla barra di navigazione verticale sulla sinistra

5) Creare un database di nome "db-ecom" (Senza apicetti)

6) Cliccare su "Account utenti", sulla barra di navigazione orizzontale ed, in corrispondenza degli utenti "root", cliccare su "Modifica privilegi"

7) Sotto alla voce sopracitata, apparirà la voce "Cambia password", inserire e re-inserire quindi "root" (Senza apicetti) come password, premendo poi "Esegui", in basso a destra.

8) Ri-eseguire l' operazione per tutti e due gli altri utenti "root"

9) A seguito di questa operazione, phpMyAdmin non vi permetterà più di accedervi, motivo per cui vi chiedo di aprire i due ticket, in modo da poter entrare e sistemare da remoto il file che si occupa del login.

10) Modificare o assicurarsi della correttezza delle prime tre stringhe, che dovrebbero riportare quanto segue:

spring.datasource.url = jdbc:mysql://localhost:3306/db-ecom&serverTimezone=Europe/Rome
spring.datasource.username = root
spring.datasource.password = root

(L'ultima parte della stringa, di sicuro, @Tomislaw-design può trovarla in uno dei vecchi progetti effettuati con il prof. Distante, questa è stata la prima che ho trovato, dovrebbe comunque andar bene.)

**CHIUNQUE DOVESSE RISOLVERE IL PROBLEMA, SCRIVA UN COMMENTO SOTTO QUESTO TICKET, IN CASO CONTRARIO, CONTATTATEMI IN PRIVATO PER VELOCIZZARE I TEMPI DI RISPOSTA**

**Comment by Prisoscar** [comment]
ma non è meglio creare un altro utenrte che il root potremmo utilizzarlo anche al di fuori di questo progetto

**Comment by rdef98** [comment]
Era per non "complicare" le cose più del dovuto più che altro

**Comment by Prisoscar** [comment]
poi è più facile creare un altro utente che modificare il root ogni volta

**Comment by rdef98** [comment]
Il fatto è che alla fine i procedimenti sono più o meno gli stessi, qualunque cosa si faccia

**Comment by rdef98** [comment]
L' unica cosa è che si potrebbe "tagliare" la parte di phpMyAdmin, quello sì

**Comment by Prisoscar** [comment]
per creare un nuovo utente basta mettere nome utente passw mettere i privilegi e finisce li la storia non va modificato altro

**Comment by luca-lezzerini** [comment]
Non credete sia ora di chiudere questo ticket?
