### ISSUE TITLE
Dubbi sulla struttura (PER IL PROF LEZZERINI)

### ISSUE THREAD

**Issue by Prisoscar** [luca-lezzerini/ecomm-jpr-01#33]
Ciao prof, noi del gruppo 1 stiamo cercando di capire come gestire gli scambi tra spring e angular e specialmnete su come fare la ricerca, siamo indecisi se prendere tutti gli elementi dal database e filtrarli su angular o mandare direttamente a spring la stringa col criterio di ricerca e fargli fare a lui la selezione degli elementi componibili

**Comment by luca-lezzerini** [comment]
Dovete mandare su Spring la stringa del campo di ricerca. Qui dovete fare una query sui campi dell'entità.
Che entità state gestendo?

**Comment by Prisoscar** [comment]
il colore per adesso

**Comment by luca-lezzerini** [comment]
Mettete nel repository questo metodo:

List<Colore> findByColoreLike(String s);

e cercate usando le wildcard di MySQL ossia % e _.
Esempio: ver% trova tutti i colori che iniziano per ver
%a% trova tutti i colori che contengono la lettera a.
Se sufficiente chiudete il ticket, sennò ditemi cosa vi serve

**Comment by Prisoscar** [comment]
Ciao prof, il  tutto pare funzionare, l'unica cosa è che se cerchi stringa vuota "%%" ti da come risultato tutti i colori.
È questo quello che volevamo ottenere o bisogna fare in altro modo per ricevere tutti i colori?

**Comment by luca-lezzerini** [comment]
E' corretto che con %% trovi tutto. Vi consiglio di fare che se inserite stringa vuota nella ricerca il client manda "%%" così trova tutti i record con il campo vuoto

**Comment by Prisoscar** [comment]
Ma così facendo come dovremmo implementare il caso cerca tutto, perché nelle specifiche non è previsto un bottone cercatutto.

**Comment by luca-lezzerini** [comment]
Esatto, implementatelo. Vedrete che non è difficile ...

**Comment by luca-lezzerini** [comment]
Avete fatto?

**Comment by Prisoscar** [comment]
no io purtroppo non potrò più fare nulla fino a martedì o mercoledì, non so il resto del team come sta messo, però comunque la ricerca normale funziona

**Comment by Prisoscar** [comment]
credo di aver finito 23f20cb
