### ISSUE TITLE
Problemi Ritorno dati server client

### ISSUE THREAD

**Issue by Nunez1337** [luca-lezzerini/ecomm-jpr-01#34]
Non riusciamo a far capire ad Angular che il dato di risposta e' un array di oggetti di tipo Categoria.
Allego il sorgente.
[server.txt](https://github.com/luca-lezzerini/ecomm-jpr-01/files/5027795/server.txt)
[client.txt](https://github.com/luca-lezzerini/ecomm-jpr-01/files/5027796/client.txt)

**Comment by luca-lezzerini** [comment]
Cambiate il controller come segue:

@RequestMapping("/cercaCategoria")
    @ResponseBody
    public List<Categoria> cercaCategoria(@RequestBody String descrizione) {
        return srvCat.cercaCategoria(descrizione);
}

Ovviamente dovete allineare anche il service.

Inoltre cambiate il client:

cerca() {
    let p = this.criterioRicerca;
    let ox: Observable<Categoria[]> =
      this.http.post<Categoria[]>(this.urlHost + "/cercaCategoria", p);
    let ss: Subscription = ox.subscribe(
      r => this.lista = r.                                               
    );
  }

**Comment by luca-lezzerini** [comment]
E studiate di più ...

**Comment by luca-lezzerini** [comment]
Manca il numero di commit. Riaperto il ticket.

**Comment by Nunez1337** [comment]
2fe3617
