### ISSUE TITLE
Richiesta modifica file comuni angular

### ISSUE THREAD

**Issue by Prisoscar** [luca-lezzerini/ecomm-jpr-01#36]
Chiara ti prego fammi aggiungere un bottone su app-component.ts e .html per poter raggiungere la pagina crudcolore per poter provare se funziona. Se accetti la richiesta al più presto metto il bottone pure per crudtaglie

**Comment by Chiara2408** [comment]
Certo, vai con la modifica. Questa mattina ho proposto la gestione dei ticket attraverso i capigruppo, in modo da sapere chi vuole intervenire su una certa cosa e assegnargli i ticket per evitare sovrapposizioni. Altrimenti, senza comunicazione, sarà impossibile sapere se è stata già presa in gestione. 
La procedura la trovi sul gruppo, ora la riposto e ti assegno il ticket che hai richiesto.

**Comment by Prisoscar** [comment]
Ho fatto 36b772c

Il tuo bottone l'ho fatto rosa
