### ISSUE TITLE
Chiarimenti campo modifica

### ISSUE THREAD

**Issue by Nunez1337** [luca-lezzerini/ecomm-jpr-01#37]
Il gruppo 2 si chiedeva se il caricamento della riga nel campo conferma sia locale oppure il client manda una richiesta al server per selezionare la riga e  un'altra richiesta per modificarla effettivamente.

**Comment by luca-lezzerini** [comment]
Bravissimi, ottima domanda, significa che state capendo i meccanismi client server.
Quando chiedete la modifica di una riga della tabella, il sistema esegue le seguenti operazioni:

> Prende localmente i dati della riga da modificare

> Richiede al server il valore aggiornato della riga

> Popola i campi del form dati con i valori ricevuti dal server

> Se confermato Salva su db e ricarica i dati della tabella, se annullato si limita a ricaricare la tabella

Fatemi sapere se vi servono altri dettagli

**Comment by Nunez1337** [comment]
Non riusciamo a far tornare la lista creata localmente nel service.
Allego pezzi del sorgente.

[client.txt](https://github.com/luca-lezzerini/ecomm-jpr-01/files/5042152/client.txt)
[server.txt](https://github.com/luca-lezzerini/ecomm-jpr-01/files/5042153/server.txt)

**Comment by umbe99** [comment]
il gruppo 2 ha risolto il problema per la lista
