### ISSUE TITLE
Modifiche su app-component.html e homepage.app.component.html

### ISSUE THREAD

**Issue by Chiara2408** [luca-lezzerini/ecomm-jpr-01#38]
Modifica dell'header nell'homepage, perché questi dati della Home:

Nome Home-page (Portale E-Commerce...) e
Bottoni Home, Anagrafiche, Carrello 

persistano su tutte le pagine del sito.

**Comment by Chiara2408** [comment]
**Note: crudColoreTEST e crudTagliaTEST, che sono tali per fare una prova visto che le pagine Anagrafiche e Carrello non sono ancora state implementate nell'app-component.ts**

**Comment by rdef98** [comment]
72e965f493ed1b59af8d75b624f5c30c9d5ba9c8
Ticket concluso.
