### ISSUE TITLE
Compiti per casa

### ISSUE THREAD

**Issue by Prisoscar** [luca-lezzerini/ecomm-jpr-01#4]
Ciao professore, ma cosa dovremmo fare esattamente per lunedì come compito per casa?

**Comment by luca-lezzerini** [comment]
Buon pomeriggio, il compito per casa consiste nel dettagliare i processi sottostanti alle coreografie Evasione dell'ordine e Spedizione, di cui trova un'immagine qui sotto.
![homework1](https://user-images.githubusercontent.com/47611629/87227142-26683e80-c399-11ea-888c-38c4621216a2.jpg)

Inoltre, se le rimane tempo, come esercizio opzionale, dovrebbe produrre il diagramma di collaborazione anche per le coreografie del Processo di acqusito-Coreografie principali, di cui allego altra immagine.
Ma si tratta di un esercizio opzionale, che comunque faremo più avanti. Ovviamente dovrà lavorare in gruppo.
![Coreografie principali](https://user-images.githubusercontent.com/47611629/87227184-81019a80-c399-11ea-9a61-9568c4259104.png)
