### ISSUE TITLE
Disabilitare pulsante

### ISSUE THREAD

**Issue by dinodipe** [luca-lezzerini/ecomm-jpr-01#41]
Vorrei disabilitare il pulsante "modifica" una volta inviati i dati al form, ma non so come fare. Può darmi delle delucidazioni in merito?

**Comment by dinodipe** [comment]
Allego frammento di codice html:
<table border="2" class="w3-table-all w3-large">
  <tr>
    <td>ID</td>
    <td>DESCRIZIONE</td>
    <td></td>
    <td></td>
  </tr>
  <tr *ngFor="let l of listaCategoria;index as i">
    <td>{{l.id}}</td>
    <td>{{l.descrizione}}</td>
    <td><button (click)="selezionaModifica(listaCategoria[i])">MODIFICA</button></td>
    <td><button (click)="rimuovi(listaCategoria[i].id)">RIMUOVI</button></td>
  </tr>
</table>

**Comment by dinodipe** [comment]
Allego frammento di codice html:
[Modifica.txt](https://github.com/luca-lezzerini/ecomm-jpr-01/files/5052602/Modifica.txt)

**Comment by luca-lezzerini** [comment]
Facile: basta cercare su Google e si trova https://www.netjstech.com/2020/04/angular-disable-button-example.html?m=1Buon lavoroSent from my Wiko W_C860Il 10 ago 2020 20:07, dinodipe <notifications@github.com> ha scritto:
Assigned #41 to @luca-lezzerini.

**Comment by dinodipe** [comment]
Leggendo attentamente le specifiche sugli stati dove viene spiegato cosa succede cliccando su  "Ricerca" oppure su "Modifica" ho utilizzato "document.getElementById("name_id").style.display="none/block"; per rendere visibile o invisibile i vari form.

**Comment by dinodipe** [comment]
Aggiornamento visibilità form: ho utilizzato *ngIf="!isShow" , togliendo "document.getElementById("name_id").style.display="none/block"
