### ISSUE TITLE
Collegamento dto non riuscito 

### ISSUE THREAD

**Issue by skrunex** [luca-lezzerini/ecomm-jpr-01#49]
sto provando da giorni a collegare a implementare il dto in taglia avendo creato le classi tagliaDto e listaTaglia dto 
poi ho preso spunto dal gruppo che aveva fatto colore perche a loro funziona il dto riescono a visualizzare sul browser il risultato atteso quindi avendo possiamo dire a questo punto copiato per filo  e per segno e ricontrollato mille volte che sia giusto e dopo aver effettuato i test con i console log e con i system-out della rispettiva parte sia server che client si è visto che il codice viene eseguito su tutte e due le parti entrando ed uscendo dai rispettivi metodi ma nonostante cio nel momento che si va a schiacciare sul bottone creato appositamente sulla parte html non restituisce nulla ma come detto prima aprendo la console di angular e il output di netbeans lui entra esegue la query ed esce senza nessun problema. arrivato a questo punto non saprei quale potrebbe essere il problema l'unica cosa che mi è rimasta da pensare e che sia un errore dalla parte html che non fa visualizzare i dati richiesti.
![Immagine](https://user-images.githubusercontent.com/67907611/92323969-60725b80-f03d-11ea-90c2-1a8122981f4c.png)
![Immagine 22png](https://user-images.githubusercontent.com/67907611/92324003-b0e9b900-f03d-11ea-9df3-14fffaccdabb.png)

**Comment by luca-lezzerini** [comment]
Sto esaminando il problema ...

**Comment by luca-lezzerini** [comment]
Il problema sembra essere nel nome del campo che contiene nei DTO la lista delle taglie.
Lato server si chiama: taglie
Lato client si chiama:  listaTaglie
Il mapper JSON lato client riceve una richiesta HTTP con un oggetto siffatto: {token: ... taglie: ...} e lo mappa sul DTO indicato nell'Observable ma non riesce a trovare nessun campo taglie nel DTO lato server e quindi valorizza a undefined il campo con tutti gli effetti da lei indicati (non mostra i dati).
Questa è l'ipotesi. Ora la verifico ...

**Comment by luca-lezzerini** [comment]
Per farlo ho cambiato il client chiedendo di mostrarmi cosa riceve. Il codice modificato è il seguente:

let ss: Subscription = b.subscribe(
      c => {
        console.log("Ricevuto il DTO: ", c);
        this.listaTaglia = c.listaTaglie;
      }
    );

**Comment by luca-lezzerini** [comment]
Ho fatto questa modifica perché mi aspetto che c non abbia il valore atteso nel campo listaTaglie ma undefined e che, dallo strumento network, si veda che il DTO di risposta abbia valorizzato taglie correttamente.
Sto eseguendo il codice ...

**Comment by luca-lezzerini** [comment]
Risposta (vista dallo strumento Network): 
{"token":{"id":4,"token":1700486538726805421,"creazione":"2020-09-06T13:47:12.0699825","scadenza":"2020-09-06T14:17:12.0699825"},"taglie":[]}
Come può notare è correttamente valorizzato il campo taglie (è vuoto perché il mio DB è ancora vuoto).
Sulla console mostra:
Ricevuto il DTO:  
{token: {…}, taglie: Array(0)}
taglie: []
token: {id: 4, token: 1700486538726805500, creazione: "2020-09-06T13:47:12.0699825", scadenza: "2020-09-06T14:17:12.0699825"}__proto__: Object
Come vede, anche qui c'é solo taglie mentre il suo codice usa listaTaglie.
Ora provo mettendo un paio di dati nel DB ...

**Comment by luca-lezzerini** [comment]
Aggiungi mi genera un errore, per cui inserisco i dati a mano sul DB.

**Comment by luca-lezzerini** [comment]
Ho inserito tre taglie.
Questo è quanto appare sulla console:
Ricevuto il DTO:  
{token: {…}, taglie: Array(3)}
taglie: Array(3)
0: descrizione: "XL"id: 1sigla: "XL"__proto__: Object1: {id: 2, descrizione: "XXL", sigla: "XXL"}2: {id: 3, descrizione: "S", sigla: "S"}length: 3__proto__: Array(0)token: {id: 5, token: -5181526386091210000, creazione: "2020-09-06T13:52:32.1435983", scadenza: "2020-09-06T14:22:32.1435983"}__proto__: Object

Sullo strumento network, nella risposta, si vede:
{"token":{"id":5,"token":-5181526386091210116,"creazione":"2020-09-06T13:52:32.1435983","scadenza":"2020-09-06T14:22:32.1435983"},"taglie":[{"id":1,"descrizione":"XL","sigla":"XL"},{"id":2,"descrizione":"XXL","sigla":"XXL"},{"id":3,"descrizione":"S","sigla":"S"}]}

Come vede, eccezion fatta per il nome del campo (taglie invece di listaTaglie) è tutto corretto.

**Comment by luca-lezzerini** [comment]
Dov'è quindi l'errore?
L'errore sta nel nome del campo del DTO che deve essere **I D E N T I C O** lato client e server e che deve avere un tipo dati COMPATIBILE (ma questo avviene nel suo caso) tra i due lati client e server.
Possiamo individuare due punti in cui c'è l'errore:

- nella definizione del DTO lato server

- nella definizione DTO lato client

Per risolverlo, decido di cambiare la lambda lato client (è l'operazione meno invasiva).
Ora procedo, testo e poi incollo il codice modificato nel prossimo commento.

-

**Comment by luca-lezzerini** [comment]
Codice prima della modifica:
let ss: Subscription = b.subscribe(
      c => {
        console.log("Ricevuto il DTO: ", c);
        this.listaTaglia = c.listaTaglie; // qui abbiamo l'errore: _listaTaglie_ non esiste in c in quanto si chiama _taglie_
      }
    );

Inoltre, nella .ts, abbiamo la seguente dichiarazione:
listaTaglia: Taglia[] = new Array(); // sbagliata in quanto il template referenzia listaTaglie: <tr *ngFor="let a of listaTaglie">


Codice dopo la modifica:
La subscribe viene modificata:
let ss: Subscription = b.subscribe(
      c => {
        console.log("Ricevuto il DTO: ", c);
        this.listaTagli**e** = c.**taglie**; // qui sono cambiati entrambi i lati dell'=
      }
    );

La classe .ts viene cambiata per allineare il nome del membro sinistro dell'= di cui sopra:
listaTagli**e**: Taglia[] = new Array();

**Comment by luca-lezzerini** [comment]
Testato:
![Clipboard01](https://user-images.githubusercontent.com/47611629/92325338-fe6c2300-f049-11ea-9555-7163f392e953.png)

**Comment by luca-lezzerini** [comment]
Codice al commit: a43290c42a25dfa8edf2b4bb2094358787cf5441

**Comment by luca-lezzerini** [comment]
Per cortesia, verifichi il funzionamento e mi faccia sapere se ci sono problemi, altrimenti chiuda il ticket.
Grazie e buona domenica
