### ISSUE TITLE
Lambda in type script

### ISSUE THREAD

**Issue by Prisoscar** [luca-lezzerini/ecomm-jpr-01#8]
Ciao professore ma in Angular è possibile passare un'interfaccia come argomento di un metodo analogamente a come possiamo fare in java o dobbiamo fare in altro modo per poter creare funzioni lambda personalizzate?

**Comment by luca-lezzerini** [comment]
Se la sua domanda si riferisce a passare un parametro alla lambda diverso da quelli già previsti nell'interfaccia funzionale, basta che usi una variabile locale.EsempioVoglio che l'età sia superiore ad un "certo valore", cioè ad un parametro non previsto dall'interfaccia funzionale:let a: number = 25;... p => p.getAge() > aSpero di aver compreso la sua domanda. Altrimenti alleghi una porzione di codice di esempio e ulteriori dettagli.Sent from my Wiko W_C860Il 01 ago 2020 00:03, Prisoscar <notifications@github.com> ha scritto:
Assigned #8 to @luca-lezzerini.

**Comment by Prisoscar** [comment]
![lambda](https://user-images.githubusercontent.com/67907720/89100121-eecb4000-d3f4-11ea-9e93-9c1d3825d0ce.PNG)
![lambda ts](https://user-images.githubusercontent.com/67907720/89100125-f2f75d80-d3f4-11ea-8a62-0b9c82de9098.PNG)
![lmbda ts 2](https://user-images.githubusercontent.com/67907720/89100128-f5f24e00-d3f4-11ea-909f-22942d142027.PNG)


La mia domanda era che in java per fare le lambda ad un certo momento ci siamo ritrovati ad inserire una interfaccia funzionale come parametro di un metodo, in typescript però pare che questa cosa non la accetti, dice cannot find name 'Cerca'.

**Comment by Prisoscar** [comment]
P.S. mi ero scordato l'export nell'interfaccia  💩 🥇 pare accetti l'argomento
